### PR TITLE
Proposed change to path for config

### PR DESCRIPTION
**Pull request by AbsolemJackdaw**
Change FabricLoader obtained path to relative java io path
L100
from 'Path path = FabricLoader.getInstance().getConfigDir();'
to     'Path path = Path.of("./config");'
suggested as by #1

### CODE REVIEW

**Comment by magistermaks** [comment]
You should probably also remove the fabric loader import line https://github.com/magistermaks/fabric-simplelibs/blob/master/simple-config/SimpleConfig.java#L24

**Comment by magistermaks** [comment]
ok this broke it, nice @ArtixAllMighty
reverting back

**Comment by AbsolemJackdaw** [comment]
You asked for an import change that i wasnt able to apply yet. What broke exactly ? This change works great on the mod im using it with. No issues outside of dev either for as far as i can tell

**Comment by magistermaks** [comment]
it fails to compile as there is no `Path.of()`
at least on java 8

**Comment by AbsolemJackdaw** [comment]
did some research, and java's nio Path.of() has indeed been added in java 11

**Comment by magistermaks** [comment]
hmm with the current game requiring java 17 anyway i probably should just add it in
i used it in an 1.16 project but tbf i don't need to update it there
so ok i will merge it again and add a disclaimer that it requires java 11, and maybe add a second legacy fabric version :thinking:

**Pull request merged**
